// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyazmrgvbcufrayoampc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5YXptcmd2YmN1ZnJheW9hbXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NjQxNDEsImV4cCI6MjA3NDU0MDE0MX0.0rCJZDE92LIbEASCH3Wyv7HwlHtuX3OgFzDT11w-NEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});